### ISSUE TITLE
Function to predict amount of charge

### ISSUE THREAD

**Issue by Ryan-Bauroth** [DurhamAcademy/NuxtScoutingSystem#206]
Create a function in the pit.vue file. This function will use the amount of time passed since a battery was plugged in and the initial voltage to predict the voltage of the current battery. In order to do this, you will need to come up with an equation for the predicted voltage based on either trials in lab or research.

Params:
- Initial time (HH:MM:SS) of a single battery
- Initial voltage (%) of a single battery

Return:
- Predicted voltage for the battery

**Comment by PrestonSwigart** [comment]
Not sure if we will actually do this.
